Adding client/server compilation and Connection impl

diff --git a/.toolchain/compile b/.toolchain/compile
--- a/.toolchain/compile
+++ b/.toolchain/compile
@@ -4,9 +4,17 @@
 
 runProgram() (
     if [ ${buildType} = Debug ]; then
-        valgrind ./${binaryPath} || exit $?
+        valgrind ./${binaryPath} ${argv1} || exit $?
     else
-        ./${binaryPath} || exit $?
+        ./${binaryPath} ${argv1} || exit $?
+    fi
+)
+
+runProgram2() (
+    if [ ${buildType} = Debug ]; then
+        valgrind ./${binaryPath2} ${argv2} || exit $?
+    else
+        ./${binaryPath2} ${argv2} || exit $?
     fi
 )
 
@@ -16,15 +24,19 @@ compiler=clang++
 buildDir=.build
 cxxVersion=23
 buildType=Release
-binaryName=$(basename `git rev-parse --show-toplevel`)
+binaryName=xrnNetwork_client
+binaryName2=xrnNetwork_server
 binaryPath=${buildDir}/sources/bin/${binaryName}
+binaryPath2=${buildDir}/sources/bin/${binaryName2}
+argv1="127.0.0.1 8080"
+argv2="8080"
 parallel=$(nproc)
 
 # -------------------------------------------------------------------------------------------------
 
 declare -a listOfDisablable=("clear" "run" "cov" "coverage" "binary" "build" "color" "pch")
 getoptArgShort="hglstmdc"
-getoptArgLong="help,gcc,g\+\+,clang,clang++,setup,test,tests,tests_run,debug,makefile,clean,debug-cmake,type:,version:,compiler:,cc-compiler:,cxx-compiler:,directory:,parallel:"
+getoptArgLong="help,gcc,g\+\+,clang,clang++,setup,test,tests,tests_run,debug,makefile,clean,debug-cmake,server,type:,version:,compiler:,cc-compiler:,cxx-compiler:,directory:,parallel:"
 
 
 
@@ -57,6 +69,7 @@ Options (* only applies if cmake is setup):
                                   ($buildDir by default)
         --parallel=NUMBER         Specify the number of core to use
                                   ($parallel by default)
+        --server                  Run second binary (used for client/server programming)
         --no-*                    Values:
                                     clear: Do not clear the screen when running the script
                                     build: Do not build the project
@@ -100,6 +113,9 @@ setupCmake() {
     else
         cmakeCommands+="-DENABLE_BINARY=OFF "
     fi
+    if [ ${runSecondBinary} = true ]; then
+        cmakeCommands+="-DCOMPILE_SERVER=true "
+    fi
     cmake \
         -S. \
         -B${buildDir} \
@@ -119,13 +135,23 @@ build() {
 }
 
 run() {
-    if [ ! -f "./${binaryPath}" ]; then
-        echo -e "${bold}${red}[ERROR]${normal}: the binary file './${binaryPath}' does not exist. Try to:" 1>&2
-        echo -e "    - ${bold}${red}Resolve${normal} the invalid script arguments" 1>&2
-        echo -e "    - ${bold}${red}Fix${normal} compilation errors" 1>&2
-        echo -e "    - Run the script again with the '-s' argument" 1>&2
+    if [ ${runSecondBinary} = true ]; then
+        if [ ! -f "./${binaryPath2}" ]; then
+            echo -e "${bold}${red}[ERROR]${normal}: the binary file './${binaryPath2}' does not exist. Try to:" 1>&2
+            echo -e "    - ${bold}${red}Resolve${normal} the invalid script arguments" 1>&2
+            echo -e "    - ${bold}${red}Fix${normal} compilation errors" 1>&2
+            echo -e "    - Run the script again with the '-s' argument" 1>&2
+        fi
+        runProgram2
+    else
+        if [ ! -f "./${binaryPath}" ]; then
+            echo -e "${bold}${red}[ERROR]${normal}: the binary file './${binaryPath}' does not exist. Try to:" 1>&2
+            echo -e "    - ${bold}${red}Resolve${normal} the invalid script arguments" 1>&2
+            echo -e "    - ${bold}${red}Fix${normal} compilation errors" 1>&2
+            echo -e "    - Run the script again with the '-s' argument" 1>&2
+        fi
+        runProgram
     fi
-    runProgram
 }
 
 clean() {
@@ -175,6 +201,7 @@ cleanNeeded=false
 stopAfterCleanNeeded=false
 debugCmakeNeeded=false
 pchNeeded=true
+runSecondBinary=false
 
 compilerModified=false
 cc_compilerModified=false
@@ -295,6 +322,7 @@ while [ $# -gt 0 ]; do
     --version) shift; cxxVersion=$1  ;;
     --directory) shift; buildDir=$1  ;;
     --parallel) shift; parallel=$1  ;;
+    --server) shift; runSecondBinary=true ;;
     --no-*)
         if [[ $1 == *"-clear-"* ]] || [[ $1 == *"-clear" ]]; then
             clearNeeded=false;
